name: Echo Task
description: Echoes an input message
inputs:
  message:
    description: 'Message to echo'
    required: true
runs:
  using: composite
  steps:
    - name: Echo output
      run: echo "Message: ${{ inputs.message }}"
      shell: bash