name: Echo Task
description: Echoes an input message
inputs:
  message:
    description: 'Message to echo'
    required: true
    default: ''
runs:
  using: composite
  steps:
    - shell: bash
      run: echo "Message: ${{ inputs.message }}"