# Actions/custom-processor/action.yml
name: Custom Processor
description: Coordinates two jobs via workflows
inputs:
  message:
    description: 'Initial message'
    required: true
runs:
  using: composite
  steps:
    - run: echo "Starting workflows with message: ${{ inputs.message }}"
    - id: job1
      uses: koushik309/Workflows/.github/workflows/workflow-job1.yml@main
      with:
        input_value: ${{ inputs.message }}
    - run: echo "Job 1 result: ${{ steps.job1.outputs.result }}"
    - id: job2
      uses: koushik309/Workflows/.github/workflows/workflow-job2.yml@main
      with:
        job1_output: ${{ steps.job1.outputs.result }}
