name: 'Orchestrate Jobs'
description: 'Runs two jobs in Workflow repository'
inputs:
  input_data:
    description: 'Initial input data'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "${{ inputs.input_data }}"